# image: docker:stable

stages:
  - build
  - test
  - deploy

before_script:
  - docker info
  
build_iz_tool:
  stage: build
  script: docker build -t hitdevenv .
  
test_apis:
  stage: test
  script:
    - command_to_test_api.sh

deploy to hit dev server:
  stage: deploy
  script:
    - use_ansible_to_deploy.sh
  when: manual
