image: docker:stable

stages:
  - build
  - test
  - deploy

before_script:
  - docker info
  
build_iz_tool:
  stage: build
  script: docker build -t hitdevenv .
  
test_apis:
    stage: test
  script:
    - # test

deploy to hit dev server:
    stage: deploy
    script:
        - # deploy
    when: manual
